# Generated by Django 2.0.1 on 2018-01-09 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('material', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeve_color', models.CharField(max_length=250)),
                ('body_color', models.CharField(max_length=250)),
                ('neck_line_color', models.CharField(max_length=250)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Cloth')),
            ],
        ),
    ]
