# Generated by Django 2.0.1 on 2018-01-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180109_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='cloth',
            new_name='Jacket',
        ),
    ]
