# Generated by Django 2.0.1 on 2018-01-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180109_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='Jacket',
            new_name='jacket',
        ),
    ]
