# Generated by Django 2.0.1 on 2018-01-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180109_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='jacket',
            new_name='cloth',
        ),
    ]
