# Generated by Django 2.0.1 on 2018-01-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180111_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
